[build]
builder = "nixpacks"
buildCommand = "composer install --no-dev && npm ci && npm run build"

[deploy]
startCommand = "php artisan serve --host=0.0.0.0 --port=$PORT"
healthcheckPath = "/up"
restartPolicyType = "ON_FAILURE"

[deploy.envs]
APP_ENV = "production"
APP_DEBUG = "false"